--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 04/07/2024 14:54:45
-- Server version: 5.7.43-log
-- Client version: 4.1
--
-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */
;
-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */
;
-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';
DROP DATABASE IF EXISTS todo_list;
CREATE DATABASE todo_list CHARACTER SET utf8 COLLATE utf8_general_ci;
--
-- Set default database
--
USE todo_list;
--
-- Create table `task`
--
CREATE TABLE task (
    idTask int(5) NOT NULL AUTO_INCREMENT,
    libTask varchar(255) NOT NULL,
    PRIMARY KEY (idTask)
) ENGINE = INNODB,
AUTO_INCREMENT = 98,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;
--
-- Create table `products`
--
CREATE TABLE products (
    product_id int(5) NOT NULL,
    product_name varchar(100) NOT NULL
) ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;
-- 
-- Dumping data for table task
--
INSERT INTO task
VALUES (65, 'Préparer la nourriture'),
    (66, 'Servir la nourriture'),
    (96, 'Chercher les enfants à 10h');
-- 
-- Dumping data for table products
--
-- Table todo_list.products does not contain any data (it is empty)
-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */
;
-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */
;